
services:

  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: finance
    volumes:
      - ./postgres-data:/var/lib/postgresql/data