"""update_expenses_cascade

Revision ID: 06bdc12bcd87
Revises: 4d5d8dee9b14
Create Date: 2025-01-10 12:54:20.021861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bdc12bcd87'
down_revision: Union[str, None] = '4d5d8dee9b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planned_expenses_group_id_fkey', 'planned_expenses', type_='foreignkey')
    op.drop_constraint('planned_expenses_user_id_fkey', 'planned_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'planned_expenses', 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'planned_expenses', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planned_expenses', type_='foreignkey')
    op.drop_constraint(None, 'planned_expenses', type_='foreignkey')
    op.create_foreign_key('planned_expenses_user_id_fkey', 'planned_expenses', 'user_profile', ['user_id'], ['id'])
    op.create_foreign_key('planned_expenses_group_id_fkey', 'planned_expenses', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
