"""update_transaction_ondelete_cat

Revision ID: 2a75ce5be0ab
Revises: 146ad5ad9b51
Create Date: 2025-03-05 17:21:19.803484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a75ce5be0ab'
down_revision: Union[str, None] = '146ad5ad9b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('finance_transactions_category_id_fkey', 'finance_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'finance_transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.create_foreign_key('finance_transactions_category_id_fkey', 'finance_transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
