"""update_debt_cascade

Revision ID: 356075b09011
Revises: eb9ce37bb5bf
Create Date: 2025-01-12 16:50:46.495135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356075b09011'
down_revision: Union[str, None] = 'eb9ce37bb5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('debts_user_id_fkey', 'debts', type_='foreignkey')
    op.create_foreign_key(None, 'debts', 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.create_foreign_key('debts_user_id_fkey', 'debts', 'user_profile', ['user_id'], ['id'])
    # ### end Alembic commands ###
