"""create_goal_contrib

Revision ID: 9b098c292421
Revises: 356075b09011
Create Date: 2025-02-03 20:29:37.328446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b098c292421'
down_revision: Union[str, None] = '356075b09011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('contributed_at', sa.DateTime(), nullable=False),
    sa.Column('is_active_pay', sa.Boolean(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goals', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('goals_group_id_fkey', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('goals', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_group_id_fkey', 'goals', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('goals', 'account_id')
    op.drop_table('goal_contributions')
    # ### end Alembic commands ###
