"""update_group_member

Revision ID: aa362257841c
Revises: 7fbc66bdd3dd
Create Date: 2025-01-05 18:40:14.440813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa362257841c'
down_revision: Union[str, None] = '7fbc66bdd3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_members_group_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_group_id_fkey', 'group_members', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
