"""update_goal_cascade

Revision ID: eb9ce37bb5bf
Revises: 4ac9ea3e9683
Create Date: 2025-01-11 13:24:17.364228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9ce37bb5bf'
down_revision: Union[str, None] = '4ac9ea3e9683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goals_group_id_fkey', 'goals', type_='foreignkey')
    op.drop_constraint('goals_user_id_fkey', 'goals', type_='foreignkey')
    op.create_foreign_key(None, 'goals', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'goals', 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.create_foreign_key('goals_user_id_fkey', 'goals', 'user_profile', ['user_id'], ['id'])
    op.create_foreign_key('goals_group_id_fkey', 'goals', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
