"""deleteGOOGLEandYANDEXtoken

Revision ID: f0a053a1e77d
Revises: 9207d51ad060
Create Date: 2024-12-16 19:28:02.961073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a053a1e77d'
down_revision: Union[str, None] = '9207d51ad060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'yandex_access_token')
    op.drop_column('user_profile', 'google_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('google_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('yandex_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
